// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    CreateNft: typeof import('./components/CreateNft.vue')['default']
    CreateNftM: typeof import('./components/CreateNftM.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    Feature: typeof import('./components/Feature.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    MImage: typeof import('./components/MImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Started: typeof import('./components/Started.vue')['default']
    WalletModal: typeof import('./components/WalletModal.vue')['default']
  }
}
